Bloggie.Web/Models/Domain/BlogPost.cs
using System.Collections;
using System.ComponentModel.DataAnnotations;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Bloggie.Web.Models.Domain
{
    // BlogPost schema
    public class BlogPost
    {
        public Guid Id { get; set; }
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string Conetent { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public DateTime PublishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }
        public ICollection<Tag> Tags { get; set; }

        // It represents a collection navigation property in Entity Framework.
        // Used to define a one-to-many or many-to-many relationship.
        // Tells EF Core that "one entity can have many related entities".
    }
}

Bloggie.Web/Models/Domain/Tag.cs
namespace Bloggie.Web.Models.Domain
{
    // Tag table Schema
    public class Tag
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public ICollection<BlogPost> BlogPost { get; set; }
    }
}

Bloggie.Web/Models/ErrorViewModel.cs
namespace Bloggie.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bloggie.Web/Models/ViewModel/AddingTagRequest.cs
namespace Bloggie.Web.Models.ViewModel
{
    public class AddingTagRequest
    {
        public string Name { get; set; }
        public string DisplayName { get; set; }

    }
}

Bloggie.Web/Models/ViewModel/EditTagRequest.cs
namespace Bloggie.Web.Models.ViewModel
{
    public class EditTagRequest
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
    }
}

Bloggie.Web/Controllers/AdminTagsController.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModel;
using Bloggie.Web.Repositoris;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bloggie.Web.Controllers
{
    public class AdminTagsController : Controller
    {
        // This is shifted to Repo's so now here we call here the Interfce

        //// Dependency injection of DbContext
        //private readonly BloggieDbContext _context;
        //public AdminTagsController(BloggieDbContext context) // Cntrl + .
        //{
        //    _context = context;
        //}


        private readonly ITagRepositary _tagsRepositary;
        public AdminTagsController(ITagRepositary iTagRepo)
        {
            _tagsRepositary = iTagRepo;
        }


        // ------------------
        // Get Action method for ADD()
        // ------------------
        [HttpGet]
        public IActionResult Add()
        {
            return View();
            // cntrl + .
        }

        // Explanation of types of data submission in two different ways
        // ----------------------------------------------
        //// 1st method (Form Submission)
        //[HttpPost]
        //[ActionName("Add")] // We gave function Name as SubmitTag but in real the Action name is "Add"
        //public IActionResult SubmitTag()
        //{
        //    // In Add.cshtml we added "name" tabs to bothe the input fields, so they will come and stored here.
        //    // (We are calling them here in controller)
        //    // In .cshtml we use "name"
        //    var name = Request.Form["name"];
        //    var displayName = Request.Form["displayName"];
        //    return View("Add");
        //}


        //// 2nd method (Data Binding) 
        //// Here what we are doing is creating ViewModel and denoting there and calling them here. 
        //// In .cshtml we use "asp-for"
        //[HttpPost]
        //public IActionResult SubmitTag(AddingTagRequest addingTagRequest)
        //{
        //    var name = addingTagRequest.Name;
        //    var displayName = addingTagRequest.DisplayName;
        //    return View("Add");
        //}


        // ----------------------
        // Post method using Add() (Create Operation)
        // ----------------------

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddingTagRequest request) // here we are using AddingTagRequest because its a model reference
        {
            // Mapping AddTagRequest to Tag domain model
            var tag = new Tag
            {
                Name = request.Name,
                DisplayName = request.DisplayName,
            };

            await _tagsRepositary.AddTagAsync(tag); // Now changes like adding and saving is done in repo file we are just calling the function

            return RedirectToAction("List"); // redirect to List page
        }





        // ------------------------------
        // Get to display all the Tags (Read operation)
        // ------------------------------

        [HttpGet]
        [ActionName("List")]  // Explicity assigning action name
        public async Task<IActionResult> List()
        {
            var tags = await _tagsRepositary.GetAllAsync();
            return View(tags);
        }





        // ----------------------------------
        // Edit the tags (Get the Udate Operation page) 
        // ----------------------------------

        // This is only the Get method for Edit (which helps in displaying)
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id) // id parameter spell should match with the asp-route-{---} bracketed spell
        {

            var tag = await _tagsRepositary.GetByIdAsync(id);
            if (tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName,
                };

                return View(editTagRequest);

            }

            return View(null);
        }




        // ----------------------------------
        // Edit the tags (Update Operation) 
        // ----------------------------------

        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {

            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName,
            };

            var updatedTag = await _tagsRepositary.UpdateTagAsync(tag);

            if (updatedTag != null)
            {
                // Show success notification
            }
            else
            {

            }

            //show failure notification
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }




        // ---------------------------
        // Delete Tag 
        // ---------------------------
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
            var deletedTag = await _tagsRepositary.DeleteTagAsync(editTagRequest.Id);

            if (deletedTag != null)
            {
                // success notification
                return RedirectToAction("List");
            }

            // Show an error notification
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }
    }
}

Bloggie.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Bloggie.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bloggie.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bloggie.Web/Views/AdminTags/Add.cshtml
@model Bloggie.Web.Models.ViewModel.AddingTagRequest //Here I am telling my application that this is my model I am using

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1> Add New Tag - Admin Functinallity </h1>
    </div>
</div>

<div class="container py-5">
    <form method="post"> 
        <div class="mb-3">
             <label class="form-label"> Name </label>
             <input type="text" class="form-control" id="name" name="name" asp-for="Name" /> 
        </div>
        <div class="mb-3">
            <label class="form-label"> Display Name </label>
            <input type="text" class="form-control" id="displayName" name="displayName"asp-for="DisplayName"/>
        </div>
        <div class="mb-3"> 
            <button type="submit" class="btn btn-dark"> Submit </button>
        </div>
    </form>
</div>

Bloggie.Web/Views/AdminTags/Edit.cshtml
@model Bloggie.Web.Models.ViewModel.EditTagRequest


<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1> Edit Tag - Admin Functionality </h1>
    </div>
</div>

<div class="container py-5">
    @if(Model != null)
    {
        <form method="post">
            <div class="mb-3">
                <label class="form-label"> Id </label>
                <input type="text" id="id" class="form-control" asp-for="Id" readonly />
            </div>

            <div class="mb-3">
                <label class="form-label"> Name </label>
                <input type="text" id="name" class="form-control" asp-for="Name" />
            </div>


            <div class="mb-3">
                <label class="form-label"> Display Name </label>
                <input type="text" id="displayname" class="form-control" asp-for="DisplayName" />
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-dark"> Update </button>
                <button type="submit" class="btn btn-danger ms-2" asp-area="" asp-controller="AdminTags" asp-action="Delete"> Delete </button>
            </div>
        </form>
    }
    else
    {
        <p> Tag Not Found </p>
    }
</div>

Bloggie.Web/Views/AdminTags/List.cshtml
@model List<Bloggie.Web.Models.Domain.Tag> // Here I am keeping in List because I am getting tags here as a List.



<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1> Show All Tag </h1>
    </div>
</div>

@* We need to use model biniding to display tags *@
<div class="container py-8">
    @if(Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th> Actions </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var tag in Model)
                {
                    <tr>
                        <td>@tag.Id</td>
                        <td> @tag.Name</td>
                        <td> @tag.DisplayName</td>
                        <td>
                            <a asp-area="" asp-controller="AdminTags" asp-action="Edit"
                            asp-route-id="@tag.Id"> Edit </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No tags found !</p>
    }
</div>

Bloggie.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bloggie.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bloggie.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bloggie.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bloggie.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Add">Add Tag</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="List"> Show All Tags</a></li>
                                @* <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li> *@
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Bloggie.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>